export const ActionTypes = {
    EMPLOYEE_LOADING: "EMPLOYEE_LOADING",
    EMPLOYEE_LOADING_SUCCESS: "EMPLOYEE_LOADING_SUCCESS",
    EMPLOYEE_LOADING_ERROR: "EMPLOYEE_LOADING_ERROR",
    CREATE_EMPLOYEE : "CREATE_EMPLOYEE",
    RETRIEVE_EMPLOYEES: "RETRIEVE_EMPLOYEES",
    UPDATE_EMPLOYEE:  "UPDATE_EMPLOYEE",
    DELETE_EMPLOYEE: "DELETE_EMPLOYEE"
}